# Generated by Django 5.2.7 on 2025-10-26 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutMe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter your full name', max_length=100)),
                ('title', models.CharField(blank=True, help_text='Optional: your current title or role', max_length=100, null=True)),
                ('bio', models.TextField(blank=True, help_text='Write a brief biography about yourself')),
                ('email', models.EmailField(blank=True, help_text='Enter your email address', max_length=254)),
            ],
            options={
                'verbose_name': 'Personal Information',
                'verbose_name_plural': 'Personal Information',
            },
        ),
        migrations.CreateModel(
            name='LearningJourney',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of your learning milestone', max_length=200)),
                ('description', models.TextField(help_text='Describe what you learned and how it helped you')),
                ('date', models.DateField(auto_now_add=True, help_text='Date when this milestone was added')),
            ],
            options={
                'verbose_name': 'Learning Milestone',
                'verbose_name_plural': 'Learning Milestones',
                'ordering': ['-date'],
            },
        ),
    ]
