# Generated by Django 5.2.7 on 2025-10-29 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dzJourney', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningjourney',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload an image for this milestone', null=True, upload_to='journey_images/'),
        ),
        migrations.AlterField(
            model_name='aboutme',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='aboutme',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='aboutme',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='aboutme',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='learningjourney',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='learningjourney',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='learningjourney',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
